### ISSUE TITLE
help: how to filter and show only video ?

### ISSUE THREAD

**Issue by skydig** [oza6ut0ne/rattice#1]
is it possible?
thanks

**Comment by oza6ut0ne** [comment]
Currently not.
I'll think about it later.

**Comment by oza6ut0ne** [comment]
@skydig https://github.com/oza6ut0ne/rattice/commit/9d75befa8fd754c7fbabf74219cebb9d892072dd
Added options `--filter-dir`/`--filter-file` and corresponding query parameters `filter_dir`/`filter_file` to filter directories and/or files with regular expressions.
For example you can show only mp4 files by `--filter-file '\.mp4$'`.

This will be included in v0.3.0 release. Probably this weekend.
If you would like to try soon, you can build latest source code yourself.

**Comment by oza6ut0ne** [comment]
Released.
